import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import {useState} from "react"
import {ListBox} from "~/components/list_box"
import {SearchField} from "~/components/search_field"
import {Item, Section} from 'react-stately';
import { v4 as uuidv4 } from 'uuid'
import Fuse from 'fuse.js'

const TodoList = ({selected, items, onSelectionChange, query}) => {
  const fuse = new Fuse(items, {keys: ['title']})
  const filteredItems = !!query ? fuse.search(query).map(item => item.item) : items

  return (
    <ListBox
      selectionMode="multiple"
      selectedKeys={selected}
      onSelectionChange={onSelectionChange}
    >
      {filteredItems.map(item =>
        <Item key={item.id}>{item.done && (<span className="pr-3 text-green-500">D</span>)}{item.title}</Item>
      )}
    </ListBox>
  );
};

const TodoAction = ({selected, setSelected, items, setItems}) => {
  const done = () => {
    setItems(items.map((item) => {
      if (Array.from(selected).includes(item.id.toString())){
        return { ...item, done: true}
      }
      return item
    }))
    setSelected(new Set([]))
  }

  const remove = () => {
    setItems(items.filter(item => !Array.from(selected).includes(item.id.toString())))
    setSelected(new Set([]))
  }

  return (
    <div className="flex w-full">
      <button className="bg-green-500 w-full rounded-l py-2 text-white" onClick={done}>Done</button>
      <button className="bg-red-500 w-full rounded-r py-2 text-white" onClick={remove}>Remove</button>
    </div>
  )
}

const Home: NextPage = () => {
  const [query, setQuery] = useState("");
  const [items, setItems] = useState([]);
  const [selected, setSelected] = useState(new Set([]));

  const addTodo = todoTitle => {
    const item = {title: todoTitle, id: uuidv4(), done: false}
    setItems([...items, item])
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center dark:bg-slate-900">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight dark:text-white sm:text-[5rem]">
            <span className="text-pink-600">TODO</span> App
          </h1>
          <div className="w-full space-y-6">
            <SearchField placeholder="Search..." onChange={setQuery} onSubmit={addTodo} />
            <TodoList items={items} selected={selected} onSelectionChange={setSelected} query={query}/>
            <TodoAction selected={selected} items={items} setItems={setItems} setSelected={setSelected} />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
